theme: jekyll-theme-architect
title: [VERB Replication Package]
description: [the replication package for Detecting Inconsistent API Functionality Descriptions in Reference Documentation and Developer Questions
]
show_downloads: true
is_user_page: true
github.is_user_page: true